#include "minecraft/ContainerScanner.h"
#include "minecraft/Nbt.h"

#include <filesystem>
#include <fstream>

namespace sanbucraft::minecraft {
namespace {
std::uint32_t be32(const std::uint8_t* bytes) { return (static_cast<std::uint32_t>(bytes[0]) << 24U) | (static_cast<std::uint32_t>(bytes[1]) << 16U) | (static_cast<std::uint32_t>(bytes[2]) << 8U) | bytes[3]; }
bool isContainer(const std::string& id) { return id == "minecraft:chest" || id == "minecraft:trapped_chest" || id == "minecraft:barrel" || id == "minecraft:shulker_box" || id.find("_shulker_box") != std::string::npos || id == "minecraft:ender_chest"; }
std::vector<ItemStack> readItems(const NbtTag* tag) { std::vector<ItemStack> result; if (!tag || !tag->list()) return result; for (const auto& entry : *tag->list()) { ItemStack item; item.id = entry.find("id") ? entry.find("id")->stringOr() : "minecraft:air"; item.count = static_cast<int>(entry.find("Count") ? entry.find("Count")->integerOr() : 0); item.slot = static_cast<int>(entry.find("Slot") ? entry.find("Slot")->integerOr(-1) : -1); if (item.count > 0 && item.id != "minecraft:air") result.push_back(item); } return result; }
void readEntities(const NbtTag* listTag, const std::string& dimension, std::vector<Container>& output) { if (!listTag || !listTag->list()) return; for (const auto& tag : *listTag->list()) { const std::string type = tag.find("id") ? tag.find("id")->stringOr() : ""; if (!isContainer(type)) continue; Container container; container.type = type; container.dimension = dimension; container.x = static_cast<int>(tag.find("x") ? tag.find("x")->integerOr() : 0); container.y = static_cast<int>(tag.find("y") ? tag.find("y")->integerOr() : 0); container.z = static_cast<int>(tag.find("z") ? tag.find("z")->integerOr() : 0); container.id = dimension + ":" + std::to_string(container.x) + ":" + std::to_string(container.y) + ":" + std::to_string(container.z); container.items = readItems(tag.find("Items")); output.push_back(std::move(container)); } }
bool scanRegion(const std::filesystem::path& path, const std::string& dimension, std::vector<Container>& output, std::string& error) { std::ifstream input(path, std::ios::binary); std::vector<std::uint8_t> header(8192); if (!input.read(reinterpret_cast<char*>(header.data()), header.size())) { error = "Cannot read region header: " + path.string(); return false; } for (int index = 0; index < 1024; ++index) { const std::uint32_t location = be32(header.data() + index * 4); const std::uint32_t sector = location >> 8U; const std::uint32_t sectors = location & 0xffU; if (sector == 0 || sectors == 0) continue; input.seekg(static_cast<std::streamoff>(sector) * 4096); std::uint8_t sizeBytes[4]; if (!input.read(reinterpret_cast<char*>(sizeBytes), 4)) { error = "Truncated chunk header in " + path.string(); return false; } const std::uint32_t size = be32(sizeBytes); if (size < 2 || size > sectors * 4096 - 4) { error = "Invalid chunk size in " + path.string(); return false; } std::uint8_t compression = 0; input.read(reinterpret_cast<char*>(&compression), 1); std::vector<std::uint8_t> payload(size - 1); if (!input.read(reinterpret_cast<char*>(payload.data()), payload.size())) { error = "Truncated chunk payload in " + path.string(); return false; } if (compression != 1 && compression != 2 && compression != 3) { error = "Unsupported Anvil compression type in " + path.string(); return false; } NbtTag root; std::string parseError; if (!NbtReader::read(payload, root, parseError)) { error = "Cannot parse chunk in " + path.string() + ": " + parseError; return false; } readEntities(root.find("block_entities"), dimension, output); if (const auto* level = root.find("Level")) readEntities(level->find("TileEntities"), dimension, output); } return true; }
}
bool ContainerScanner::scan(const std::string& worldPath, std::vector<Container>& containers, std::string& error) { namespace fs = std::filesystem; containers.clear(); const std::pair<fs::path, std::string> dimensions[] = {{fs::path(worldPath) / "region", "minecraft:overworld"}, {fs::path(worldPath) / "DIM-1" / "region", "minecraft:the_nether"}, {fs::path(worldPath) / "DIM1" / "region", "minecraft:the_end"}}; for (const auto& [directory, dimension] : dimensions) { if (!fs::exists(directory)) continue; for (const auto& entry : fs::directory_iterator(directory)) if (entry.is_regular_file() && entry.path().extension() == ".mca" && !scanRegion(entry.path(), dimension, containers, error)) return false; } return true; }
}
